version: "3"

services:

  database:
    image: mongo
    container_name: nest-db
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: poemaemvideo
      # MONGO_INITDB_ROOT_USERNAME: poemaemvideo
      # MONGO_INITDB_ROOT_PASSWORD: poemaemvideo

  api:
    build:
      context: ./back-end
    container_name: nest-api
    ports: 
      - "3000:3000"
    volumes: 
      - ./back-end:/home/api
    depends_on: 
      - database